# fly.toml file generated for wdi-json-flix on 2022-02-22T15:32:03+01:00

app = "wdi-json-flix"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

# [build]
#   builder = "heroku/buildpacks:20"

[build.args]
  BUNDLE_WITHOUT = "development:test"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
